language: python
cache: pip
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py -q install
script:
- pytest
notifications:
  email: true
jobs:
  include:
    - stage: deploy
      python: "3.6"
      deploy:
        provider: pypi
        user: skar404
        password:
          secure: WcBP35DE9Qyc8Oegs/4vd97GNACSEfGAEWEAhQl27opp9xKDZvZ9WlUKa31DE8U+zRxDm0NlkLOqdnBJ4/AlPmey9Zz8gDnUqyi6qgzDhubHxMJoDuCd85ADU4z29hRXY3jxXYFULuM5S4kM6BO8CsX87Fi4/5hdRNM14zIb7BmX7+bEvaUkCWMWYyowfB4tTVgBld8n3VBa98SrJJ3GmBmGGEDIMvTOdC7a5xv6Ra5tjroSIa0aQwmdvsOEVGeL54cMdavkZNvnCZvTW9PgX+wBapFEVMB+jo3hvw1L85k5B87iqLKMO/lixGaPGJGkNiFMlfXeVo6vQjzGNOER5p5uVhB5H6s55qY97r5wzc5/nCfF1id6tEMRmkrPT7Sdr8WdVhRnW1TS5GZWKSLkrjwPsnYlwzqOweaPJlPNvTVbKDUbFD+UxATXOr5AT01fStoR3fcOpupY0+UGvrUp1o3Y0PwpRXL0im8GrN94gmcAPwF1lKQDvrUbIRFDefz5i4BvfG3Hpo9SIPgqwkqgn9+ZtnL7JR7aSL7UZ3yfXZFoXr0UmkYKy1aochQiQSHOzgRzYXqa5GVq6wgi/kFNjUeva9g/Wb8FOz52rHjQkoY4a7L4fvooZlEiO0aB8Bm5NhYQh+VC6YmqPvaN8zXYOpr8yjNi6QVki4rf1yBWZvk=
        on:
          distributions: sdist bdist_wheel
          repo: skar404/pptx-template
